refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  metrics:
    kind: rolling_file
    path: log/atp-metrics.log
    policy:
      kind: compound
      roller:
        kind: fixed_window
        count: 10
        base: 1
        pattern: log/atp-metrics.{}.log
      trigger:
        kind: size
        limit: 10mb
    encoder:
      pattern: "{d(%FT%T%.9f%:z)} - {m}{n}"

  application:
    kind: rolling_file
    path: log/atp-tunnel.log
    policy:
      kind: compound
      roller:
        kind: fixed_window
        count: 10
        base: 1
        pattern: log/atp-tunnel.{}.log
      trigger:
        kind: size
        limit: 10mb
    encoder:
      pattern: "{d(%FT%T%.9f%:z)} - [{l}] {f}:{L} - {m}{n}"

root:
  level: warn
  appenders:
    - application

loggers:
  metrics:
    level: info
    appenders:
      - metrics
    additive: false
